name: Claude PR Creation
on:
  issue_comment:
    types: [created]

jobs:
  create-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          prompt: "${{ github.event.comment.body }}"
          allowed_tools: [
            "Bash(git status)",
            "Bash(git log)",
            "Bash(git diff)",
            "View",
            "GlobTool"
            # 必要に応じて他のツールも追加できます
          ]
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
