name: Claude PR Creation
on:
  issue_comment:
    types: [created]

permissions:
  issues: write     # Issueへのコメント書き込みに必要
  contents: write   # ★★★ これが重要！ブランチ作成やコード変更に必要 ★★★
  pull-requests: write # もしClaudeがPRを作成するなら、これも追加しておくと良い

jobs:
  create-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          allowed_tools: "Bash(git status),Bash(git log),Bash(git diff),View,GlobTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # model: "claude-3-opus-20240229"
