name: Claude PR Creation
on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      # ↓↓↓ このステップを追加 ↓↓↓
      - name: Checkout code
        uses: actions/checkout@v4 # または @v3 など、最新の安定バージョン

      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          allowed_tools: "Bash(git status),Bash(git log),Bash(git diff),View,GlobTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # model: "claude-3-opus-20240229"
